name: Docker Image Downloader

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '请输入完整的 Docker 镜像名 (例如: halohub/halo:2.22.14)'
        required: true
        default: 'halohub/halo:2.22.14'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Pull Docker Image
        run: |
          docker pull ${{ github.event.inputs.image_name }}

      - name: Save Docker Image to Tar
        run: |
          SAFE_NAME=$(echo "${{ github.event.inputs.image_name }}" | sed 's/[:\/]/_/g')
          FILE_NAME="${SAFE_NAME}.tar"
          docker save ${{ github.event.inputs.image_name }} -o $FILE_NAME
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v-${{ github.run_id }}"
          name: "镜像打包完成: ${{ github.event.inputs.image_name }}"
          body: "请在下方 Assets 区域下载您的 .tar 镜像文件。"
          draft: false
          prerelease: false
          files: ${{ env.FILE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
